# World  {.tabset .tabset-fade .tabset-pills}

```{r}
my.world <- my.corona %>% 
    group_by(type, date) %>%
    summarise(cases = sum(cases), population = sum(population)) %>%
    arrange(date) %>%
    group_by(type) %>% 
    mutate(state = 'World',
           cumul = cumsum(cases),
           population = max(population, na.rm = TRUE))
```

## Totals

```{r}
ommit.start(my.world, 'all', params$confirmed.start)
```

## log2 scale

```{r, warning=FALSE}
ommit.start(my.world, 'all', params$confirmed.start, log2.flag = TRUE)
```

## New Confirmed cases

```{r}
my.world.last.days <- filter.last.days(my.world, params$last.days)
```

```{r}
last.days(my.world.last.days, 'all', params$last.days, c(), log2.flag = FALSE, per.100k.flag = FALSE, new.flag = TRUE)
```

## New Deaths

```{r}
last.days(my.world.last.days, 'all', params$last.days, c(), log2.flag = TRUE, per.100k.flag = FALSE, new.flag = TRUE)
```

## Rolling average of previous 4 days

```{r}
last.week.world <- filter.last.days.cumulative(my.world, 4)
```

```{r}
last.week.cumulative(last.week.world, 'all', 4, c(), log2.flag = FALSE, per.100k.flag = FALSE)
```

## Rolling average of previous 4 days *(log2 scale)*

```{r}
last.week.cumulative(last.week.world, 'all', 4, c(), log2.flag = TRUE, per.100k.flag = FALSE)
```


# World per 100k population  {.tabset .tabset-fade .tabset-pills}

## Totals

```{r}
ommit.start(my.world, 'all', params$confirmed.start, per.100k.flag = TRUE)
```

## *log2 scale*

```{r, warning=FALSE}
ommit.start(my.world, 'all', params$confirmed.start, per.100k.flag = TRUE, log2.flag = TRUE, digits = 2)
```

## New Confirmed cases

```{r}
last.days(my.world.last.days, 'all', params$last.days, c(), log2.flag = FALSE, per.100k.flag = TRUE, new.flag = TRUE)
```

## New Deaths

```{r}
last.days(my.world.last.days, 'all', params$last.days, c(), log2.flag = TRUE, per.100k.flag = TRUE, new.flag = TRUE)
```

## Rolling average of previous 4 days

```{r}
last.week.cumulative(last.week.world, 'all', 4, c(), log2.flag = FALSE, per.100k.flag = TRUE)
```

## Rolling average of previous 4 days *(log2 scale)*

```{r}
last.week.cumulative(last.week.world, 'all', 4, c(), log2.flag = TRUE, per.100k.flag = TRUE)
```

