---
title: "Bayern covid-19 analysis"
output: 
    html_document:
        toc: true
        dev: 'svg'
params:
    death.start: !r 5
    confirmed.start: !r 100
    duplicate.every: !r 2
    last.days: !r 12
---

```{r, child='_header.md'}
```

```{r render.me, include=FALSE, eval=FALSE}
rmarkdown::render('bayern.Rmd', quiet = TRUE)
```

```{r render.site, include=FALSE, eval=FALSE}
rmarkdown::render_site(quiet = TRUE)
rmarkdown::render_site()
rmarkdown::clean_site()
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, collapse = TRUE, fig.width = 10, fig.height = 8)
library(tidyverse)
library(dplyr)
library(viridis) # color pallete
library(ggrepel)
library(zoo)
library(glue)
library(DT)
library(loose.rock)
library(anytime)
library(scales)
library(futile.logger)
library(wbstats) # world bank data
library(reshape2)
library(eurostat)

devtools::load_all()

Sys.setlocale('LC_TIME', 'en_GB.UTF-8')
.Last.value <- flog.layout(layout.format('~m'))
```

# Data

Data was retrieved from *'RamiKrispin/coronavirus'* R data package which is updated daily in github.com.

It's not realtime data and data presented may have 1 or more days of difference from real-time data. Check the caption on the figures to check when was the last data point.


```{r buildCorona, echo=FALSE, message=FALSE, warning=FALSE}
eu.de <- download.de.data()

my.corona.original <- eu.de$data

source.by = eu.de$source
```

```{r eurostat}
populations <- download.eurostat.population('DE')

my.corona <- my.corona.original %>% left_join(populations, by = 'state')

my.corona <- my.corona %>% 
    ungroup %>%
    mutate(state.data = factor(state, levels = my.corona %>% filter(type == 'confirmed') %>% summarise(cases = max(cumul)) %>% arrange(cases) %>% pull(state)),
           state = state) %>%
    group_by(state)
```

```{r}
last.date          <- format(max(my.corona.original$date), '%Y/%m/%d')
last.date.string   <- paste0('Latest date from ', last.date, ' (source: ', source.by, ')')
region.code        <- 'State'
region.code.plural <- 'States'

countries                <- 'Bayern'
countries.always.include <- my.corona$state %>% unique
countries.extended       <- countries.always.include
```





```{r, include=FALSE, eval=FALSE}
#
#
#
#
#
#
#
#
#
#
#
#
#
#     BELOW should be always the same
#
#
#
#
#
#
#
#
#
#
#
#

```

```{r, child='_main.Rmd'}
```

## All states

```{r}
death.vs.cases.plot(death.vs.cases, always.include = countries.always.include)
```

## Data

```{r}
death.vs.cases.data(death.vs.cases) %>% datatable()
```

## Number of Confirmed Cases

```{r}
my.corona.original %>% filter(state %in% countries.extended) %>% cases.plot('confirmed')
```

## Number of Deaths

```{r}
my.corona.original %>% filter(state %in% countries.extended) %>% cases.plot('death')
```
