---
title: "Germany covid-19 analysis"
output: 
    html_document:
        toc: true
        dev: 'svg'
params:
    death.start: !r 5
    confirmed.start: !r 100
    duplicate.every: !r 2
    last.days: !r 12
---

```{r, child='_header.md'}
```

```{r render.me, include=FALSE, eval=FALSE}
rmarkdown::render('germany.Rmd', quiet = TRUE)
```

```{r render.site, include=FALSE, eval=FALSE}
rmarkdown::render_site(quiet = TRUE)
rmarkdown::render_site()
rmarkdown::clean_site()
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, collapse = TRUE, fig.width = 10, fig.height = 8)
library(tidyverse)
library(dplyr)
library(viridis) # color pallete
library(ggrepel)
library(zoo)
library(glue)
library(DT)
library(anytime)
library(loose.rock)
library(scales)
library(futile.logger)
library(wbstats) # world bank data
library(reshape2)
library(eurostat)

BiocManager::install('averissimo/covid19.de.data')
BiocManager::install('averissimo/covid19.pt.data')

devtools::load_all()

Sys.setlocale('LC_TIME', 'en_GB.UTF-8')
.Last.value <- flog.layout(layout.format('~m'))
```

```{r buildCorona, echo=FALSE, message=FALSE, warning=FALSE}
eu.de <- download.de.data(by.federal.state = TRUE)

my.corona.original <- eu.de$data

source.by = eu.de$source
```

```{r eurostat}
populations <- download.eurostat.population('DE')

my.corona <- my.corona.original %>% left_join(populations, by = 'state')

my.corona <- my.corona %>% 
    ungroup %>%
    mutate(state.data = factor(state, levels = my.corona %>% filter(type == 'confirmed') %>% summarise(cases = max(cumul)) %>% arrange(cases) %>% pull(state)),
           state = state) %>%
    group_by(state)
```

```{r}
last.date          <- format(max(my.corona.original$date), '%Y/%m/%d')
last.date.string   <- paste0('Latest date from ', last.date, ' (source: ', source.by, ')')
region.code        <- 'State'
region.code.plural <- 'States'
region.all         <- 'Germany'

countries                <- my.corona$state %>% unique
countries.always.include <- my.corona$state %>% unique
countries.extended       <- countries.always.include
```

```{r}
after.100.dat = list(all = filter.after(my.corona, params$death.start, params$confirmed.start)) # my.corona.after.100
after.100.dat$confirmed = ommit.data(after.100.dat$all, 'confirmed', countries) # my.corona.after.100.confirmed.dat
after.100.dat$death = ommit.data(after.100.dat$all, 'death', countries) # my.corona.after.100.death.dat

last.days.dat <- filter.last.days(my.corona, params$last.days) # my.corona.last.days
last.week.dat <- filter.last.days.cumulative(my.corona, 4) # last.week
death.vs.cases <- filter.death.vs.cases(last.week.dat) %>% filter(state %in% countries.extended) # death.vs.cases

my.world = list()
my.world$main <- my.corona %>% 
    group_by(type, date) %>%
    summarise(cases = sum(cases), population = sum(population)) %>%
    arrange(date) %>%
    group_by(type) %>% 
    mutate(state = region.all,
           state.code = region.all,
           cumul = cumsum(cases),
           population = max(population, na.rm = TRUE))
my.world$last.days <- filter.last.days(my.world$main, params$last.days)
my.world$last.week <- filter.last.days.cumulative(my.world$main, 4)
```

```{r, include=FALSE, eval=FALSE}
#
#
#
#
#
#
#
#
#
#
#
#
#
#     BELOW should be always the same
#
#
#
#
#
#
#
#
#
#
#
#
```

```{r, child='_data.Rmd'}
```

```{r, child='_world.Rmd'}
```

```{r, child='_main.Rmd'}
```

## Data

```{r}
death.vs.cases.data(death.vs.cases) %>% datatable()
```

## Number of Confirmed Cases

```{r}
my.corona.original %>% filter(state %in% countries.extended) %>% cases.plot('confirmed')
```

## Number of Deaths

```{r}
my.corona.original %>% filter(state %in% countries.extended) %>% cases.plot('death')
```
