---
title: "Italy covid-19 analysis"
output: 
    html_document:
        toc: true
        dev: 'svg'
params:
    death.start: !r 5
    confirmed.start: !r 100
    duplicate.every: !r 2
    last.days: !r 12
---

```{r, child='_header.md'}
```

```{r render.me, include=FALSE, eval=FALSE}
rmarkdown::render('italy.Rmd', quiet = TRUE)
```

```{r render.site, include=FALSE, eval=FALSE}
rmarkdown::render_site(quiet = TRUE)
rmarkdown::render_site()
rmarkdown::clean_site()
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, collapse = TRUE, fig.width = 10, fig.height = 8)
library(tidyverse)
library(dplyr)
library(viridis) # color pallete
library(ggrepel)
library(zoo)
library(glue)
library(DT)
library(anytime)
library(loose.rock)
library(scales)
library(futile.logger)
library(wbstats) # world bank data
library(reshape2)
library(eurostat)

devtools::load_all()

Sys.setlocale('LC_TIME', 'en_GB.UTF-8')
.Last.value <- flog.layout(layout.format('~m'))
```

```{r buildCorona, echo=FALSE, message=FALSE, warning=FALSE}
eu.it <- download.it.data()

my.corona.original <- eu.it$data %>% 
    mutate(state.code = state)

source.by = eu.it$source
```

```{r eurostat}
pop.raw <- download.eurostat.population('IT', 2)

# see readme.. this is a problem between EU and IT mapping of regions
problem.states <- c('Provincia Autonoma di Bolzano/Bozen', 'Provincia Autonoma di Trento')
regions.sum <- pop.raw %>% filter(state %in% problem.states) %>% pull(population) %>% sum

populations <- pop.raw %>%
    add_row(state = 'Trentino-Aalot Adige/Südtirol', population = regions.sum) %>% 
    filter(!state %in% problem.states)
    
my.corona <- my.corona.original %>% left_join(populations, by = 'state')

my.corona <- my.corona %>% 
    ungroup %>%
    mutate(state.data = factor(state, levels = my.corona %>% filter(type == 'confirmed') %>% summarise(cases = max(cumul)) %>% arrange(cases) %>% pull(state)),
           state = state) %>%
    group_by(state)
```

```{r}
last.date          <- format(max(my.corona.original$date), '%Y/%m/%d')
last.date.string   <- paste0('Latest date from ', last.date, ' (source: ', source.by, ')')
region.code        <- 'State'
region.code.plural <- 'States'

countries                <- my.corona$state %>% unique
countries.always.include <- my.corona$state %>% unique
countries.extended       <- countries.always.include
```

```{r, include=FALSE, eval=FALSE}
#
#
#
#
#
#
#
#
#
#
#
#
#
#     BELOW is mainly generated by child: _main.Rmd
#
#
#
#
#
#
#
#
#
#
#
#
```

```{r, child='_data.Rmd'}
```

```{r, child='_main.Rmd'}
```

## All states

```{r}
death.vs.cases.plot(death.vs.cases, always.include = countries.always.include)
```

## Data

```{r}
death.vs.cases.data(death.vs.cases) %>% datatable()
```

## Number of Confirmed Cases

```{r}
my.corona.original %>% filter(state %in% countries.extended) %>% cases.plot('confirmed')
```

## Number of Deaths

```{r}
my.corona.original %>% filter(state %in% countries.extended) %>% cases.plot('death')
```
