---
title: "Portugal Mortality data"
output: 
  html_document:
    dev: 'svg'
---

```{r, eval=FALSE, include=FALSE}
rmarkdown::render('mortality.Rmd', output_file = 'mortality.md')
rmarkdown::render('mortality.Rmd', output_file = 'mortality.html')
```

```{r, eval=FALSE, include=FALSE}
rmarkdown::clean_site()
rmarkdown::render_site(quiet = TRUE)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  comment = "#>",
  fig.height = 10,
  fig.width = 10
)
devtools::load_all()
library(pdftools)
library(rvest)
library(dplyr)
library(tibble)
library(DT)
library(anytime)
library(glue)
library(reshape2)
library(zoo)
library(xml2)
library(ggplot2)
library(ggrepel)
library(plotly)

Sys.setlocale('LC_TIME', 'en_GB.UTF-8')
```

## Description & Code {.tabset .tabset-fade .tabset-pills}

This analysis retrieves data directly from the Portuguese Health ministry death certificate site ([SICO](https://evm.min-saude.pt/)) and makes an yearly comparison.

### Hide source code


### Show source code

```{r, echo=TRUE}
# Download from DGS
json <- download.evm() %>% rjson::fromJSON()

# Process into multiple columns
dat <- sapply(1 + seq_along(json$x$data[-1]), function(ix) {
  my.year <- json$x$data[[ix]]
  my.year[sapply(my.year, is.null)] <- NA
  tibble::tibble(!!as.name(2009 + ix - 2) := unlist(my.year, recursive=FALSE))
})

# Merge data
mortality <- dplyr::bind_cols(day = json$x$data[[1]], dat) %>% 
  mutate(day = factor(day, levels = day))

# Add some statistics (mean, sd, max, min)
mortality.with.stats <- mortality %>% 
  replace(is.na(.), NA) %>%
  dplyr::rowwise() %>% 
  mutate(meanPre2020 = mean(c_across(cols = -c("2020", 'day')), na.rm = TRUE),
         mean = mean(c_across(cols = -c("meanPre2020", 'day')), na.rm = TRUE),
         sdPre2020 = sd(c_across(cols = -c("2020","meanPre2020", "mean", 'day')), na.rm = TRUE),
         sd = sd(c_across(cols = -c("meanPre2020", "mean", "sdPre2020", 'day')), na.rm = TRUE)) %>% 
  mutate(maxPre2020 = max(c_across(cols = colnames(.)[colnames(mortality) != 2020][grepl('^[0-9]+$', colnames(.))]), na.rm = TRUE),
         max = max(c_across(cols = colnames(.)[grepl('^[0-9]+$', colnames(.))]), na.rm = TRUE),
         minPre2020 = min(c_across(cols = colnames(.)[colnames(mortality) != 2020][grepl('^[0-9]+$', colnames(.))]), na.rm = TRUE),
         min = min(c_across(cols = colnames(.)[grepl('^[0-9]+$', colnames(.))]), na.rm = TRUE)) %>% 
  dplyr::ungroup()
```

```{r sample_plot, eval=FALSE, echo=TRUE}
show.year.mortality(mortality.with.stats, seq(2019, 2020))
```


## Year vs. 2020 {.tabset .tabset-fade .tabset-pills}

Yearly comparison against 2020

### 2019 vs. 2020

```{r y2019}
show.year.mortality(mortality.with.stats, seq(2019, 2020))
```

### 2018 vs. 2020

```{r y2018}
show.year.mortality(mortality.with.stats, c(2018, 2020))
```

### 2017 vs. 2020

```{r y2017}
show.year.mortality(mortality.with.stats, c(2017, 2020))
```

### 2016 vs. 2020

```{r y2016}
show.year.mortality(mortality.with.stats, c(2016, 2020))
```

### 2015 vs. 2020

```{r y2015}
show.year.mortality(mortality.with.stats, c(2015, 2020))
```

### 2014 vs. 2020

```{r y2014}
show.year.mortality(mortality.with.stats, c(2014, 2020))
```

### 2013 vs. 2020

```{r y2013}
show.year.mortality(mortality.with.stats, c(2013, 2020))
```

### 2012 vs. 2020

```{r y2012}
show.year.mortality(mortality.with.stats, c(2012, 2020))
```

### 2011 vs. 2020

```{r y2011}
show.year.mortality(mortality.with.stats, c(2011, 2020))
```

### 2010 vs. 2020

```{r y2010}
show.year.mortality(mortality.with.stats, c(2010, 2020))
```

### 2009 vs. 2020

```{r y2009}
show.year.mortality(mortality.with.stats, c(2009, 2020))
```

```{r, child='_header.md'}
```