---
title: "COVID-19 Portugal data"
output: 
  html_document:
    toc: true
    dev: svg
---

```{r, eval=FALSE, include=FALSE}
rmarkdown::render('portugal.Rmd')
```

```{r, eval=FALSE, include=FALSE}
rmarkdown::clean_site()
rmarkdown::render_site(quiet = TRUE)
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
devtools::load_all()
library(pdftools)
library(rvest)
library(dplyr)
library(tibble)
library(DT)
library(anytime)
library(glue)
library(reshape2)
library(zoo)
library(xml2)
library(usethis)
library(ggplot2)
library(ggrepel)
library(plotly)
library(viridis)

Sys.setlocale('LC_TIME', 'en_GB.UTF-8')
```

```{r, include=FALSE}
BiocManager::install('averissimo/covid19.pt.data')
library(covid19.pt.data)
```

```{r child='_header.md'}
```

```{r, message=FALSE, include=FALSE}
dat    <- download.updated.pt()
dgs.pt <- dat$dgs.pt
covid19.pt  <- dat$cdc.eu
```

```{r, include=FALSE}
age.data <- dgs.pt %>% 
  reshape2::melt(id.vars = c('country', 'date'), variable.name = 'type') %>% 
  group_by(country, type) %>% 
  filter(grepl('(confirmed_|death_)', type)) %>% 
  arrange(date) %>% 
  ungroup() %>% 
  mutate(gender = if_else(grepl('.*_m_*', type), 'men', 'women'),
         age_type = if_else(grepl('confirmed_', type), 'confirmed', 'death'),
         type = gsub('.*_(m|w)_', '', type),
         value = if_else(gender == 'men', value * -1, value %>% as.double))
```

## Cumulative data for Portugal

```{r, echo=FALSE, warning=FALSE, fig.width=10, fig.height=7}
my.plot.data <- dgs.pt %>% 
  reshape2::melt(id.vars = c('country', 'date'), variable.name = 'type', measure.vars = c('tests', 'deaths', 'confirmed', 'hospitalized', 'in.icu', 'recovered')) %>% 
  filter(!is.na(value)) %>% 
  mutate(type = 
           gsub('confirmed', 'Confirmed cases', type) %>% 
           gsub('deaths', 'Deaths', .) %>% 
           gsub('recovered', 'Recovered', .) %>% 
           gsub('hospitalized', 'Hospitalized', .) %>% 
           gsub('in.icu', 'In ICU', .) %>% 
           gsub('tests', 'Tests', .)) %>% 
  mutate(text = format(value, big.mark = ',', trim = TRUE)) %>%
  ungroup() %>% 
  select(Date = date, Type = type, value = value, text = text) %>% 
  arrange(Date) 

d <- my.plot.data  %>%  
  highlight_key(~Type)

pal <- viridis(my.plot.data$Type %>% length, end = .8, option = 'A')

d %>% plot_ly() %>% 
  add_trace(x = ~Date, 
            y = ~value, 
            color = ~Type, 
            type = 'scatter',
            mode = 'lines+markers', 
            colors = pal, 
            name = ~Type,
            customdata = ~text,
            hovertemplate = paste0('<b>%{customdata}</b>', '<br><i>%{text}</i>', '<br><i>%{x}</i>'),
            text = ~Type
            ) %>% 
  layout(legend = list(x = 0.1, y = 1), dragmode = FALSE,
         title = 'Individuals that were Infected, Recovered and Died',
         xaxis = list(title = 'Date'),
         yaxis = list(title = 'Number of individuals', type = 'log')) %>% 
  highlight(on = 'plotly_click', off = 'plotly_doubleclick')
```

## Data per day

```{r, echo=FALSE, warning=FALSE, fig.width=10, fig.height=7}
my.plot.data <- dgs.pt %>% 
  reshape2::melt(id.vars = c('country', 'date'), variable.name = 'type', measure.vars = c('tests', 'deaths', 'confirmed', 'hospitalized', 'in.icu', 'recovered')) %>% 
  filter(!is.na(value)) %>% 
  mutate(type = 
           gsub('confirmed', 'Confirmed cases', type) %>% 
           gsub('deaths', 'Deaths', .) %>% 
           gsub('recovered', 'Recovered', .) %>% 
           gsub('hospitalized', 'Hospitalized', .) %>% 
           gsub('in.icu', 'In ICU', .) %>% 
           gsub('tests', 'Tests', .)) %>% 
  group_by(country, type) %>% 
  arrange(desc(date)) %>% 
  mutate(value = zoo::rollapply(value, 2, function(ix) { if(length(ix) <= 1) { return(ix) } else { ix[1] - sum(ix[-1]) } }, fill = c(0, 0, 0), align = 'left', partial = TRUE)) %>%
  mutate(text = format(value, big.mark = ',', trim = TRUE)) %>%
  ungroup() %>% 
  #filter(value != 0) %>% 
  select(Date = date, Type = type, value = value, text = text) %>% 
  arrange(Date) 

d <- my.plot.data  %>%  
  highlight_key(~Type)

pal <- viridis(my.plot.data$Type %>% length, end = .8, option = 'A')

d %>% plot_ly() %>% 
  add_trace(x = ~Date, 
            y = ~value, 
            color = ~Type, 
            type = 'scatter',
            mode = 'lines+markers', 
            colors = pal, 
            name = ~Type,
            customdata = ~text,
            hovertemplate = paste0('<b>%{customdata}</b>', '<br><i>%{text}</i>', '<br><i>%{x}</i>'),
            text = ~Type
            ) %>% 
  layout(legend = list(x = 0.1, y = 1), dragmode = FALSE,
         title = 'Individuals that were Infected, Recovered and Died',
         xaxis = list(title = 'Date'),
         yaxis = list(title = 'Number of individuals')) %>% 
  highlight(on = 'plotly_click', off = 'plotly_doubleclick')
```

# Cases / Deaths by age groups {.tabset .tabset-fade .tabset-pills}

```{r, results='asis', echo=FALSE,fig.width=4.5, warning=FALSE}
ixs <- unique(age.data %>% arrange(desc(date)) %>% pull(date))

confirmed.max <- age.data %>% filter(age_type == 'confirmed') %>%  pull(value) %>% max
death.max <- age.data %>% filter(age_type == 'death') %>%  pull(value) %>% max
for (age.ix in seq_along(ixs)) {
  age.ix.f <- ixs[age.ix]
  cat('\n')
  cat('\n')
  cat('## {age.ix.f}' %>% glue)
  cat('\n')
  cat('\n')
  
  age.data.all <- age.data %>% 
    filter(date == age.ix.f & value != 0) %>% 
    select(type, gender, age_type, value) %>% 
    reshape2::dcast(type + gender ~ age_type, mean, fill = 0) %>% 
    mutate(label.confirmed = if_else(confirmed != 0, format(abs(confirmed), big.mark = ',', trim = TRUE), NA_character_),
           label.death = if_else(death != 0, 
                                 paste0(format(abs(death), big.mark = ',', trim = TRUE),
                                        ' (',
                                        scales::percent(abs(death/confirmed), accuracy = 0.01, big.mark = ','),
                                        ')'), 
                                 NA_character_))
  
  label.death <- list(men = age.data.all %>% filter(gender == 'men') %>% pull(death) %>% sum %>% abs,
                      women = age.data.all %>% filter(gender == 'women') %>% pull(death) %>% sum %>% abs)

  label.confirmed <- list(men = age.data.all %>% filter(gender == 'men') %>% pull(confirmed) %>% sum %>% abs,
                          women = age.data.all %>% filter(gender == 'women') %>% pull(confirmed) %>% sum %>% abs)

  print(age.data.all %>%
    ggplot(aes(x = confirmed, y = type, fill = gender)) +
    geom_bar(stat = 'identity') + 
    ggrepel::geom_label_repel(aes(label = label.confirmed, fill = gender), color = 'white', direction = 'x', seed = 1985, size = 3.5,
                          nudge_x = ifelse(age.data.all$gender == 'men', -1, 1),
                          show.legend = FALSE,
                          na.rm = TRUE) +
    expand_limits(x =c(-1 * confirmed.max, confirmed.max)) +
    scale_x_continuous('', labels = function(ix) { return(abs(ix)) }) +
    scale_y_discrete(limits = age.data$type %>% unique %>% sort) + 
    scale_fill_viridis_d('', end = .8, labels = function(ix) { return(paste0(ix, ' (', format(label.confirmed[ix], big.mark = ',', trim = TRUE), ')'))}) + 
    labs(title = 'Total number of Confirmed cases ({format(label.confirmed$women + label.confirmed$women, big.mark = ",", trim = TRUE)}) by age group' %>% glue,
         y = 'Age group',
         subtitle = '',
         caption = '',
         x = 'Confirmed Cases') +
    theme_minimal() + 
    theme(legend.position = 'bottom'))
  print(age.data.all %>%
    ggplot(aes(x = death, y = type, fill = gender)) +
    geom_bar(stat = 'identity') + 
    ggrepel::geom_label_repel(aes(label = label.death, fill = gender), color = 'white', direction = 'x', seed = 1985, size = 3.5,
                              nudge_x = ifelse(age.data.all %>% filter(!is.na(label.death)) %>% pull(gender) == 'men', -1, 1),
                              show.legend = FALSE,
                              na.rm = TRUE) +
    expand_limits(x =c(-1 * death.max, death.max)) +
    scale_x_continuous('', labels = function(ix) { return(abs(ix)) }) +
    scale_fill_viridis_d('', end = .8, labels = function(ix) { return(paste0(ix, ' (', format(label.death[ix], big.mark = ',', trim = TRUE), ')'))}) + 
    labs(title = 'Total number of Deaths ({format(label.death$women + label.death$women, big.mark = ",", trim = TRUE)}) by age group' %>% glue,
         subtitle = 'Percentage shows the mortality rate',
         caption = 'Mortality rate = \'deaths\' / \'confirmed cases\'',
         y = 'Age group',
         x = 'Deaths') +
    theme_minimal() + 
    theme(legend.position = 'bottom'))
  cat('\n')
  cat('\n')
}
```

# New Cases / Deaths by age groups {.tabset .tabset-fade .tabset-pills}

```{r, include=FALSE}
# required to get the mortality rate to calculate daily predictions of new deaths
age.data.all <- age.data %>% 
  filter(date == max(date) & value != 0) %>% 
  select(type, gender, age_type, value) %>% 
  reshape2::dcast(type + gender ~ age_type, mean, fill = 0) %>% 
  mutate(label.confirmed = if_else(confirmed != 0, format(abs(confirmed), big.mark = ',', trim = TRUE), NA_character_),
         label.death = if_else(death != 0, 
                               paste0(format(abs(death), big.mark = ',', trim = TRUE),
                                      ' (',
                                      scales::percent(abs(death/confirmed), accuracy = 0.01, big.mark = ','),
                                      ')'), 
                               NA_character_))
```


```{r, results='asis', echo=FALSE,fig.width=4.5, warning=FALSE}
age.data.all.new.tmp <- age.data %>% 
  group_by(country, type, gender, age_type) %>% 
  arrange(desc(date)) %>% 
  mutate(value = zoo::rollapply(value, 2, function(ix) { if(length(ix) <= 1) { return(ix) } else { ix[1] - sum(ix[-1]) } }, fill = c(0, 0, 0), align = 'left', partial = TRUE)) %>%
  filter(value != 0) %>% 
  filter(date != min(date)) # ignore first day as it shows cumulative cases from before!

ixs <- unique(age.data.all.new.tmp %>% arrange(desc(date)) %>% pull(date))

confirmed.max <- age.data.all.new.tmp %>% filter(age_type == 'confirmed') %>%  pull(value) %>% max
death.max <- age.data.all.new.tmp %>% filter(age_type == 'death') %>%  pull(value) %>% max

dat.predicted <- tibble()

for (age.ix in seq_along(ixs)) {
  age.ix.f <- ixs[age.ix]
  
  age.data.all.new <- age.data.all.new.tmp %>% 
    filter(date == age.ix.f & value != 0) %>% 
    ungroup() %>% 
    select(type, gender, age_type, value) %>% 
    group_by(type, gender, age_type) %>% 
    reshape2::dcast(type + gender ~ age_type, mean, fill = 0) %>% 
    mutate(label.confirmed = if_else(confirmed != 0, format(abs(confirmed), big.mark = ',', trim = TRUE), NA_character_),
           label.death = if_else(death != 0, 
                                 if_else(is.na(confirmed) | confirmed == 0, format(abs(death), big.mark = ',', trim = TRUE),
                                         paste0(format(abs(death), big.mark = ',', trim = TRUE))),
                                 NA_character_)) %>% 
    inner_join(age.data.all %>% select(-label.confirmed, -label.death), by = c('type', 'gender'), suffix = c('', '.all')) %>% 
    mutate(predicted.death = if_else(death.all != 0,
                                     abs(confirmed * death.all / confirmed.all),
                                     0)) %>% 
    mutate(label.confirmed = if_else(predicted.death == 0,
                                     paste0(label.confirmed, ' (0)'),
                                     if_else(predicted.death < 0.01, 
                                             paste0(label.confirmed, ' (<0.01)'),
                                             paste0(label.confirmed, 
                                                    ' (',
                                                    format(round(predicted.death, digits = 2), big.mark = ','),
                                                    ')')))) %>% 
    select(-confirmed.all, -death.all)  
  
  dat.predicted <- dat.predicted %>% bind_rows(
    tibble(
    date = age.ix.f,
    predicted = sum(age.data.all.new$predicted.death)
  ))
  
  
  label.death <- list(men = age.data.all.new %>% filter(gender == 'men') %>% pull(death) %>% sum %>% abs,
                      women = age.data.all.new %>% filter(gender == 'women') %>% pull(death) %>% sum %>% abs)

  label.confirmed <- list(men = age.data.all.new %>% filter(gender == 'men') %>% pull(confirmed) %>% sum %>% abs,
                          women = age.data.all.new %>% filter(gender == 'women') %>% pull(confirmed) %>% sum %>% abs)
  
  label.predicted <- list(men = age.data.all.new %>% filter(gender == 'men') %>% pull(predicted.death) %>% sum %>% abs %>% round(digits = 1),
                          women = age.data.all.new %>% filter(gender == 'women') %>% pull(predicted.death) %>% sum %>% abs %>% round(digits = 1))

  cat('\n')
  cat('\n')
  cat('## {age.ix.f}' %>% glue)
  cat('\n')
  cat('\n')
  print(age.data.all.new %>%
    ggplot(aes(x = confirmed, y = type, fill = gender)) +
    geom_bar(stat = 'identity') + 
    ggrepel::geom_label_repel(aes(label = label.confirmed, fill = gender), color = 'white', direction = 'x', seed = 1985, size = 3.5,
                          nudge_x = ifelse(age.data.all.new$gender == 'men', -1, 1),
                          show.legend = FALSE,
                          na.rm = TRUE) +
    expand_limits(x =c(-1 * confirmed.max, confirmed.max)) +
    scale_x_continuous('', labels = function(ix) { return(abs(ix)) }) +
    scale_y_discrete(limits = age.data$type %>% unique %>% sort) + 
    scale_fill_viridis_d('', end = .8, labels = function(ix) { return(paste0(ix, ' ', format(label.confirmed[ix], big.mark = ',', trim = TRUE), ' (', format(label.predicted[ix], big.mark = ',', trim = TRUE), ')'))}) + 
    labs(title = 'New {format(label.confirmed$women + label.confirmed$men, big.mark = ",", trim = TRUE)} confirmed cases from {format(age.ix.f, "%B %d")}' %>% glue,
           subtitle = 'predicted deaths for age groups shown in parenthesis' %>% glue,
         caption = 'Prediction based on current \'mortality rate\' ({sum(age.data.all.new$predicted.death) %>% round(digits = 1)} deaths for {format(age.ix.f, "%B %d")})' %>% glue,
         y = 'Age group',
         x = 'Confirmed Cases') +
    theme_minimal() + 
    theme(legend.position = 'bottom'))
  print(age.data.all.new %>%
    ggplot(aes(x = death, y = type, fill = gender)) +
    geom_bar(stat = 'identity') + 
    ggrepel::geom_label_repel(aes(label = label.death, fill = gender), color = 'white', direction = 'x', seed = 1985, size = 3.5,
                              nudge_x = ifelse(age.data.all.new %>% filter(!is.na(label.death)) %>% pull(gender) == 'men', -1, 1),
                              show.legend = FALSE,
                              na.rm = TRUE) +
    expand_limits(x =c(-1 * death.max, death.max)) +
    scale_x_continuous('', labels = function(ix) { return(abs(ix)) }) +
    scale_fill_viridis_d('', end = .8, labels = function(ix) { return(paste0(ix, ' ', format(label.death[ix], big.mark = ',', trim = TRUE), ''))}) + 
    labs(title = 'New {format(label.death$women + label.death$women, big.mark = ",", trim = TRUE)} deaths from {format(age.ix.f, "%B %d")}' %>% glue,
         subtitle = '',
         caption = '',
         y = 'Age group',
         x = 'Deaths') +
    theme_minimal() + 
    theme(legend.position = 'bottom'))
  cat('\n')
  cat('\n')
}
```

```{r, eval=FALSE, include=FALSE}
# Predicted deaths based on cases and current mortality rate

# note that the predicted deaths are for the future as a result of the confirmed cases on that day
plot_ly() %>% 
  add_trace(x = ~date, y = ~predicted, data = dat.predicted, mode = 'scatter+lines')

dat.pred.tmp <- dat.predicted %>% mutate(deaths = predicted) %>% 
  select(date, deaths) %>% 
  arrange(date) %>% 
  mutate(deaths = cumsum(deaths))

tmp.dat <- dgs.pt %>% select(date, deaths) %>% 
  inner_join(dat.pred.tmp, by = 'date', suffix = c('.dgs', '.predicted')) %>% 
  melt(id.vars = 'date')

plot_ly() %>% 
  add_trace(x = ~date, y = ~value, data = tmp.dat, color = ~variable, mode = 'markers+lines', type = 'scatter')


```


# Data {.tabset .tabset-fade .tabset-pills}

## Data from DGS

```{r, echo=FALSE}
dgs.pt %>% arrange(desc(date)) %>%  datatable()
```

## Data from EU CDC updated

```{r, message=FALSE, echo=FALSE}
covid19.pt %>% datatable()
```




